const sampleListings = [
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
    {
        title: "Rustic Countryside Cottage",
        description: "Charming cottage surrounded by fields and greenery, offering a peaceful escape.",
        image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
        price: 600,
        location: "Tranquil Countryside",
        country: "France",
    },
];

module.exports = { data: sampleListings };